CREATE TABLE T7 (
  C1 NUMBER,
  C2 VARCHAR2(255),
  PRIMARY KEY (C1));
 
INSERT INTO T7
SELECT
  ROWNUM,
  LPAD(CHR(65 + ROUND(ROWNUM/1000)),255,CHR(65 + ROUND(ROWNUM/1000)))
FROM
  DUAL
CONNECT BY
  LEVEL<=1000000;
 
CREATE TABLE T8 (
  C1 NUMBER);
 
INSERT INTO T8
SELECT
  ROWNUM
FROM
  DUAL
CONNECT BY
  LEVEL<=14;
 
COMMIT;
 
EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'T7',CASCADE=>TRUE)
EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>USER,TABNAME=>'T8',CASCADE=>TRUE)


SET AUTOTRACE TRACEONLY STATISTICS
ALTER SESSION SET TRACEFILE_IDENTIFIER = '10053Transform1';
ALTER SESSION SET EVENTS '10053 trace name context forever, level 1';

SELECT 
  C1, SUBSTR(C2,1,20) C2
FROM
  T7
WHERE  
  EXISTS ( 
    SELECT 
      1 
    FROM 
      T8 
    WHERE 
      T8.C1=T7.C1);

ALTER SESSION SET TRACEFILE_IDENTIFIER = '10053Transform2';
SELECT
  C1, SUBSTR(C2,1,20) C2
FROM
  T7
WHERE
  C1 IN (
    SELECT
      T8.C1
    FROM
      T8
    WHERE
      T8.C1=T8.C1);

ALTER SESSION SET TRACEFILE_IDENTIFIER = '10053Transform3';
SELECT
  C1, SUBSTR(C2,1,20) C2
FROM
  T7
WHERE
  C1 IN (
    SELECT
      T8.C1
    FROM
      T8
    WHERE
      T8.C1=T7.C1);

ALTER SESSION SET EVENTS '10053 trace name context off'; 