SELECT
  DO.OBJECT_NAME, BH.FILE#, BH.STATUS, COUNT(*) BLOCKS
FROM
  DBA_OBJECTS DO, V$BH BH
WHERE
  DO.DATA_OBJECT_ID = BH.OBJD
  AND DO.OWNER='TESTUSER'
  AND DO.OBJECT_NAME IN ('T9')
GROUP BY
  DO.OBJECT_NAME, BH.FILE#, BH.STATUS
ORDER BY
  COUNT(*) DESC;


SELECT
  HEADER_FILE,
  HEADER_BLOCK
FROM
  DBA_SEGMENTS
WHERE
  OWNER='TESTUSER'
  AND SEGMENT_NAME='T9';


SELECT
  BH.BLOCK#,
  BH.STATUS,
  COUNT(*) CNT
FROM
  DBA_OBJECTS DO, V$BH BH
WHERE
  DO.DATA_OBJECT_ID = BH.OBJD
  AND DO.OWNER='TESTUSER'
  AND DO.OBJECT_NAME IN ('T9')
  AND BH.FILE#=7
  AND BH.BLOCK# BETWEEN 1289609 AND 1289614
GROUP BY
  BH.BLOCK#,
  BH.STATUS
ORDER BY
  BH.BLOCK#,
  BH.STATUS;