SPOOL HighChildCountPlans.txt
SET HEADING OFF
SET FEEDBACK OFF
SET ARRAYSIZE 1000
SET LINESIZE 150
SET PAGESIZE 2000

SELECT /*+ LEADING(S) USE_NL(S T) */
  T.PLAN_TABLE_OUTPUT
FROM
  (SELECT
    SQL_ID,
    CHILD_NUMBER,
    COUNT(*) OVER (PARTITION BY SQL_ID) C
  FROM
    V$SQL
  ORDER BY
    SQL_ID,
    CHILD_NUMBER) S,
  TABLE(DBMS_XPLAN.DISPLAY_CURSOR(S.SQL_ID,S.CHILD_NUMBER,'TYPICAL')) T
WHERE
  S.C>=10;

SPOOL HighChildCountReason.txt
DESC V$SQL_SHARED_CURSOR
SET LINESIZE 200
SET HEADING ON
BREAK ON SQL_ID SKIP 1

SELECT /*+ LEADING(S) USE_NL(S T) */
  SSC.*
FROM
  (SELECT
    SQL_ID,
    CHILD_NUMBER,
    COUNT(*) OVER (PARTITION BY SQL_ID) C
  FROM
    V$SQL
  ORDER BY
    SQL_ID,
    CHILD_NUMBER) S,
  V$SQL_SHARED_CURSOR SSC
WHERE
  S.C>=10
  AND S.SQL_ID=SSC.SQL_ID
  AND S.CHILD_NUMBER=SSC.CHILD_NUMBER;

SPOOL OFF
