SELECT /*+ ORDERED */
  S.SID,
  S.USERNAME,
  S.PROGRAM,
  S.STATUS,
  SW.EVENT,
  SW.WAIT_TIME,
  SW.STATE,
  SW.SECONDS_IN_WAIT,
  S.SQL_ID,
  S.SQL_ADDRESS,
  S.SQL_HASH_VALUE,
  S.SQL_CHILD_NUMBER,
  S.ROW_WAIT_OBJ#,
  S.ROW_WAIT_FILE#,
  S.ROW_WAIT_BLOCK#,
  S.ROW_WAIT_ROW#,
  SW.P1,
  SW.P2,
  SW.P3
FROM
  V$SESSION_WAIT SW,
  V$SESSION S
WHERE  
  S.USERNAME IS NOT NULL 
  AND SW.SID=S.SID 
  AND SW.EVENT NOT LIKE '%SQL*Net%' 
  AND SW.EVENT NOT IN ('Streams AQ: waiting for messages in the queue',
                       'wait for unread message on broadcast channel');


SELECT
  S.SID, S.USERNAME, S.PROGRAM, S.SQL_ID, S.SQL_ADDRESS, S.SQL_HASH_VALUE,
  S.SQL_CHILD_NUMBER, S.ROW_WAIT_OBJ#, S.ROW_WAIT_FILE#, S.ROW_WAIT_BLOCK#,
  S.ROW_WAIT_ROW#, L.LMODE, L.REQUEST, L.ID1, L.ID2, L.TYPE, L.BLOCK
FROM
  V$LOCK L,
  V$SESSION S
WHERE
  (L.ID1, L.ID2, L.TYPE) IN 
    (SELECT
      ID1, ID2, TYPE
    FROM
      V$LOCK
    WHERE
      REQUEST > 0)
  AND L.SID=S.SID;


SELECT
  DE.OWNER,
  DE.SEGMENT_NAME,
  DE.SEGMENT_TYPE,
  DE.TABLESPACE_NAME
FROM
  DBA_EXTENTS DE
WHERE
  DE.FILE_ID = 7
  AND 1466532 BETWEEN BLOCK_ID AND BLOCK_ID+BLOCKS-1;
