SELECT
  BUSY_TIME/(BUSY_TIME+IDLE_TIME)*100 PERCENT_BUSY
FROM
  (SELECT
    MAX(DECODE(TE.STAT_NAME,'BUSY_TIME',TE.VALUE-NVL(TS.VALUE,0),NULL)) BUSY_TIME,
    MAX(DECODE(TE.STAT_NAME,'IDLE_TIME',TE.VALUE-NVL(TS.VALUE,0),NULL)) IDLE_TIME
  FROM
    DATALOG.TE_OSSTAT TE,
    DATALOG.TS_OSSTAT TS
  WHERE
    TE.STAT_NAME=TS.STAT_NAME(+)
    AND TE.STAT_NAME IN ('BUSY_TIME','IDLE_TIME'));
