COMMIT;

DEFINE CAPTURE_SECONDS=600

INSERT INTO
  DATALOG.TS_SQLSTATS
SELECT
  SQL_ID, PLAN_HASH_VALUE, LAST_ACTIVE_TIME, CPU_TIME, ELAPSED_TIME, AVG_HARD_PARSE_TIME,
  APPLICATION_WAIT_TIME, CONCURRENCY_WAIT_TIME, CLUSTER_WAIT_TIME, USER_IO_WAIT_TIME,
  PLSQL_EXEC_TIME, JAVA_EXEC_TIME, PARSE_CALLS, LOADS, VERSION_COUNT, INVALIDATIONS,
  EXECUTIONS, FETCHES, ROWS_PROCESSED, BUFFER_GETS, DISK_READS, DIRECT_WRITES,
  SORTS, SHARABLE_MEM, TOTAL_SHARABLE_MEM
FROM
  V$SQLSTATS;

EXEC DBMS_LOCK.SLEEP(&&CAPTURE_SECONDS);

INSERT INTO
  DATALOG.TE_SQLSTATS
SELECT
  SQL_ID, PLAN_HASH_VALUE, LAST_ACTIVE_TIME, CPU_TIME, ELAPSED_TIME, AVG_HARD_PARSE_TIME,
  APPLICATION_WAIT_TIME, CONCURRENCY_WAIT_TIME, CLUSTER_WAIT_TIME, USER_IO_WAIT_TIME,
  PLSQL_EXEC_TIME, JAVA_EXEC_TIME, PARSE_CALLS, LOADS, VERSION_COUNT, INVALIDATIONS,
  EXECUTIONS, FETCHES, ROWS_PROCESSED, BUFFER_GETS, DISK_READS, DIRECT_WRITES,
  SORTS, SHARABLE_MEM, TOTAL_SHARABLE_MEM
FROM
  V$SQLSTATS;

COLUMN CPU_S FORMAT 9,990.00
COLUMN ELA_S FORMAT 9,990.00
COLUMN APP_S FORMAT 9,990.00
COLUMN CON_S FORMAT 9,990.00
COLUMN CLU_S FORMAT 9,990.00
COLUMN USR_S FORMAT 9,990.00

SET LINESIZE 180
SET PAGESIZE 200
SPOOL SQLSTATS.TXT

SELECT
  TE.SQL_ID, TE.PLAN_HASH_VALUE PHV,
  (TE.CPU_TIME-NVL(TS.CPU_TIME,0))/1000000 CPU_S,
  (TE.ELAPSED_TIME-NVL(TS.ELAPSED_TIME,0))/1000000 ELA_S,
  TE.PARSE_CALLS-NVL(TS.PARSE_CALLS,0) PAR_C,
  TE.EXECUTIONS-NVL(TS.EXECUTIONS,0) EXEC,
  (TE.APPLICATION_WAIT_TIME-NVL(TS.APPLICATION_WAIT_TIME,0))/1000000 APP_S,
  (TE.CONCURRENCY_WAIT_TIME-NVL(TS.CONCURRENCY_WAIT_TIME,0))/1000000 CON_S,
  (TE.CLUSTER_WAIT_TIME-NVL(TS.CLUSTER_WAIT_TIME,0))/1000000 CLU_S,
  (TE.USER_IO_WAIT_TIME-NVL(TS.USER_IO_WAIT_TIME,0))/1000000 USR_S
FROM
  DATALOG.TS_SQLSTATS TS,
  DATALOG.TE_SQLSTATS TE
WHERE
  TE.SQL_ID=TS.SQL_ID(+)
  AND TE.PLAN_HASH_VALUE=TS.PLAN_HASH_VALUE(+)
  AND (TE.ELAPSED_TIME-NVL(TS.ELAPSED_TIME,0))>=10000000
ORDER BY
  (TE.ELAPSED_TIME-NVL(TS.ELAPSED_TIME,0)) DESC;

SPOOL OFF
