CREATE GLOBAL TEMPORARY TABLE
  DATALOG.TS_SQLSTATS ON COMMIT DELETE ROWS AS
SELECT
  SQL_ID, PLAN_HASH_VALUE, LAST_ACTIVE_TIME, CPU_TIME, ELAPSED_TIME, AVG_HARD_PARSE_TIME,
  APPLICATION_WAIT_TIME, CONCURRENCY_WAIT_TIME, CLUSTER_WAIT_TIME, USER_IO_WAIT_TIME,
  PLSQL_EXEC_TIME, JAVA_EXEC_TIME, PARSE_CALLS, LOADS, VERSION_COUNT, INVALIDATIONS,
  EXECUTIONS, FETCHES, ROWS_PROCESSED, BUFFER_GETS, DISK_READS, DIRECT_WRITES,
  SORTS, SHARABLE_MEM, TOTAL_SHARABLE_MEM
FROM
  V$SQLSTATS
WHERE
  0=1;

CREATE GLOBAL TEMPORARY TABLE
  DATALOG.TE_SQLSTATS ON COMMIT DELETE ROWS AS
SELECT
  SQL_ID, PLAN_HASH_VALUE, LAST_ACTIVE_TIME, CPU_TIME, ELAPSED_TIME, AVG_HARD_PARSE_TIME,
  APPLICATION_WAIT_TIME, CONCURRENCY_WAIT_TIME, CLUSTER_WAIT_TIME, USER_IO_WAIT_TIME,
  PLSQL_EXEC_TIME, JAVA_EXEC_TIME, PARSE_CALLS, LOADS, VERSION_COUNT, INVALIDATIONS,
  EXECUTIONS, FETCHES, ROWS_PROCESSED, BUFFER_GETS, DISK_READS, DIRECT_WRITES,
  SORTS, SHARABLE_MEM, TOTAL_SHARABLE_MEM
FROM
  V$SQLSTATS
WHERE
  0=1;
