SELECT
  OWNER,
  OBJECT_NAME,
  OBJECT_TYPE
FROM
  DBA_OBJECTS
WHERE
  OBJECT_ID = 12388;


SELECT
  *
FROM
  owner.object_name
WHERE
  ROWID = DBMS_ROWID.ROWID_CREATE(1, 12388, 4, 1046809, 21);


SELECT
  S.SID,
  S.USERNAME,
  S.PROGRAM,
  S.SQL_HASH_VALUE SQL_HASH,
  L.TYPE,
  L.LMODE LM,
  L.REQUEST RQ,
  DECODE(L.BLOCK,1,'Blocker','Blocked') BLOCK,
  L.ID1,
  L.ID2
FROM
  V$LOCK L,
  V$SESSION S
WHERE
  L.SID=S.SID
  AND (L.ID1, L.ID2, L.TYPE) IN 
  (SELECT
    ID1, ID2, TYPE
  FROM
    V$LOCK
  WHERE
    REQUEST > 0);


SELECT
  EVENT,
  MAX(DECODE(WAIT_TIME_MILLI,1,WAIT_COUNT,0)) MILLI1,
  MAX(DECODE(WAIT_TIME_MILLI,2,WAIT_COUNT,0)) MILLI2,
  MAX(DECODE(WAIT_TIME_MILLI,4,WAIT_COUNT,0)) MILLI4,
  MAX(DECODE(WAIT_TIME_MILLI,8,WAIT_COUNT,0)) MILLI8,
  MAX(DECODE(WAIT_TIME_MILLI,16,WAIT_COUNT,0)) MILLI16
FROM
  V$EVENT_HISTOGRAM
WHERE
  EVENT LIKE 'db file%'
GROUP BY
  EVENT
ORDER BY
  EVENT;


