/* Sample Time Based Wait Event Collect Table */
CREATE GLOBAL TEMPORARY TABLE
  DATALOG.SYSTEM_EVENT ON COMMIT DELETE ROWS AS
SELECT
  SYSDATE CHECK_DATE,
  EVENT,
  TOTAL_WAITS,
  TOTAL_TIMEOUTS,
  TIME_WAITED,
  TIME_WAITED_MICRO
FROM
  V$SYSTEM_EVENT
WHERE
  0=1;


/* Sample Insert Into Time Based Wait Event Collect Table */
INSERT INTO
  DATALOG.SYSTEM_EVENT
SELECT
  TRUNC(SYSDATE,'MI') CHECK_DATE,
  EVENT,
  TOTAL_WAITS,
  TOTAL_TIMEOUTS,
  TIME_WAITED,
  TIME_WAITED_MICRO
FROM
  V$SYSTEM_EVENT;
  

/* Sample Time Based Wait Event Delta */
SELECT
  SE2.EVENT,
  SE2.TOTAL_WAITS-SE1.TOTAL_WAITS WAITS,
  SE2.TOTAL_TIMEOUTS-SE1.TOTAL_TIMEOUTS TIME_OUTS,
  (SE2.TIME_WAITED-SE1.TIME_WAITED)/100 SECONDS,
  ROUND((SE2.TIME_WAITED-SE1.TIME_WAITED)/(SE2.TOTAL_WAITS-SE1.TOTAL_WAITS)/100,6) AVERAGE
FROM
  DATALOG.SYSTEM_EVENT SE1,
  DATALOG.SYSTEM_EVENT SE2
WHERE
  SE1.CHECK_DATE=TO_DATE('08/03/2009 14:00','MM/DD/YYYY HH24:MI')
  AND SE2.CHECK_DATE=TO_DATE('08/03/2009 14:04','MM/DD/YYYY HH24:MI')
  AND SUBSTR(SE1.EVENT,1,5) NOT IN ('DIAG ','jobq ','rdbms','Space','SQL*N','Strea')
  AND SE1.EVENT NOT LIKE 'wait for unread%'
  AND SE1.EVENT NOT LIKE '%timer'
  AND SE2.EVENT=SE1.EVENT
  AND (SE2.TIME_WAITED-SE1.TIME_WAITED)>0
ORDER BY
  (SE2.TIME_WAITED-SE1.TIME_WAITED) DESC;