SELECT
  SQL_ID,
  COUNT(DISTINCT PLAN_HASH_VALUE) C
FROM
  PERFSTAT.STATS$SQL_PLAN_USAGE
GROUP BY
  SQL_ID
HAVING
  COUNT(DISTINCT PLAN_HASH_VALUE)>1;


SET LINESIZE 150
SET PAGESIZE 10000
SPOOL StatspackPlan.txt

SELECT /*+ ORDERED USE_NL(SPU T) */
  T.*
FROM
  (SELECT DISTINCT
     PLAN_HASH_VALUE
   FROM
     PERFSTAT.STATS$SQL_PLAN_USAGE
   WHERE
     SQL_ID='0fr8zhn4ymu3v'
   ORDER BY
     PLAN_HASH_VALUE) SPU,
  TABLE(DBMS_XPLAN.DISPLAY(
    'PERFSTAT.STATS$SQL_PLAN',
    NULL,
    'TYPICAL -PREDICATE -NOTE',
    'PLAN_HASH_VALUE='||SPU.PLAN_HASH_VALUE)) T;
